dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest
  - poetry run black --check .
  - poetry run isort --check .
  - poetry run mypy .
