dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - poetry install
script:
  - poetry run pytest
  - poetry run black --check .
  - poetry run isort --check .
  - poetry run mypy
